version: "3"

services:
  next-app:
    container_name: webirpc
    image: webirpc:latest
    ports:
      - 3000:3000
    restart: always

    # Set environment variables based on the .env file
    env_file:
      - .env
    networks:
      - backend

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  backend:
    external: true
